[env:nucleo_h743zi]
platform = ststm32
board = h743vi
board_build.ldscript = custom.ld    ; Use a custom linker script that places the .axisram section in D2 SRAM
framework = stm32cube
;board_build.mcu = stm32h743vitx
board_build.f_cpu = 400000000L

; Build configuration
build_flags = 
    -D USE_HAL_DRIVER
    -D CUBEMX
    -D HSE_VALUE=25000000U          ; <- Исправлено под 25 МГц
    -I include
    -I Core/Inc
    -I Drivers/STM32H7xx_HAL_Driver/Inc
    -I Drivers/CMSIS/Device/ST/STM32H7xx/Include
    -I Drivers/CMSIS/Include
    -Wl,-lc -Wl,-lm -Wl,-lnosys
    -mthumb
    -mcpu=cortex-m7
    -mfpu=fpv5-d16                 ; <- H743 использует FPv5, fpv4 удален
    -mfloat-abi=hard
    -Wl,--no-warn-mismatch
    -Wl,-Map=output.map
    -D USE_PWR_LDO_SUPPLY

; Source file configuration
build_src_filter = 
    +<*>
    +<Core/Src/*>
    -<Core/Src/main.c>
    +<Drivers/*>
    -<Drivers/STM32*HAL_Driver/Src/*>
    +<Drivers/CMSIS/*>
    -<Middlewares/Third_Party/FreeRTOS/*>
    +<Middlewares/*>

lib_deps = 

upload_protocol = serial
upload_port = COM10
upload_flags =
    -b 115200
    -g 0x08000000

monitor_speed = 115200